eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
server:
  port: 20001
spring:
  application:
    name: eureka-client1
  zipkin:
    base-url: http://localhost:9411/

